function parsepagelist(e){var t="calculate"
chrome.tabs.sendMessage(e,{message:t},function(e){})}function opentab(e){return stopflag?(chrome.tabs.remove(listtabid),void chrome.tabs.update(managertabid,{url:managertaburl,highlighted:!0})):void(e.length>0?chrome.tabs.getAllInWindow(currentwinid,function(t){sleep(1e3*t.length/5)
var n=e.shift()
chrome.tabs.create({url:n,selected:!1},function(t){tabids.push(t.id),opentab(e)})}):chrome.tabs.sendMessage(listtabid,{message:"nextpage",nextSelector:pageconf.nextSelector.split("{{{{{}}}}}")},function(e){}))}function genericOnClick(e,t){alert(e.linkUrl)}function selectionOnClick(e,t){chrome.tabs.sendRequest(t.id,{selectionText:e.selectionText},function(e){})}function sleep(e){for(var t=(new Date).getTime();;)if((new Date).getTime()-t>e)break}var conf={},serverurl="http://www.wangye.io/",requestType="",contentTabId="",listtabid="",conflisttabid="",confcontenttabid="",managertabid="",managertaburl="",currentwinid="",stopflag=!1,tabids=[],confid,targeturl="",pageconf={}
chrome.browserAction.onClicked.addListener(function(){chrome.windows.getCurrent(function(e){chrome.tabs.getSelected(e.id,function(t){chrome.tabs.sendMessage(t.id,{message:"conflistpage"},function(t){conflisttabid=e.id}),console.log(t.url)})})}),chrome.tabs.onUpdated.addListener(function(e,t,n){"complete"==t.status&&-1!=tabids.indexOf(n.id)?chrome.tabs.sendMessage(e,{message:"fetchDetail",fieldsconf:pageconf.fieldsSelector.split("{{{{{}}}}}")},function(t){$.ajax({url:serverurl+"savePageConfData.htm",type:"post",datatype:"json",data:{content:t,confId:pageconf.id},timeout:1e5,success:function(e,t){},fail:function(e,t){}}),tabids.splice(tabids.indexOf(n.id),1),chrome.tabs.remove(e)}):"complete"==t.status&&e==listtabid?chrome.tabs.sendMessage(e,{message:"calculate",pageconf:pageconf},function(e){}):"complete"==t.status&&e==conflisttabid?chrome.tabs.sendMessage(e,{message:"conflistpage"},function(e){}):"complete"==t.status&&e==confcontenttabid&&chrome.tabs.sendMessage(e,{message:"confcontentpage"},function(e){})}),chrome.extension.onRequest.addListener(function(e,t,n){if("save"==e.type)chrome.windows.getCurrent(function(t){chrome.tabs.getAllInWindow(t.id,function(n){currentwinid=t.id,opentab(e.urls)})})
else if("startcollect"==e.type)stopflag=!1,managertabid=t.tab.id,managertaburl=t.tab.url,$.ajax({url:serverurl+"getConfbyId.htm",type:"get",datatype:"json",data:{content:e.confid},timeout:1e5,success:function(e,t){pageconf=JSON.parse(e).pageConf,chrome.tabs.create({url:pageconf.targetUrl,selected:!1},function(e){listtabid=e.id}),n(e)},fail:function(e,t){}})
else if("stopcollect"==e.type)stopflag=!0
else if("nextpageend"==e.type)chrome.tabs.remove(listtabid),chrome.tabs.update(managertabid,{url:managertaburl,highlighted:!0})
else if("confpageprocess"==e.type)confid=e.confid,chrome.tabs.create({url:e.url},function(e){conflisttabid=e.id,n(conflisttabid)})
else if("getHtmlList"==e.type)$.ajax({url:serverurl+"getHtmlList.htm",type:"post",datatype:"text",data:{content:e.content},timeout:1e5,success:function(e,t){n(e)},fail:function(e,t){}})
else if("confcontentpage"==e.type)console.log(e.userid),conf.userid=e.userid,conf.title=e.title,conf.regex=e.regex,conf.regexarr=e.regexarr,conf.targeurl=e.targeurl,conf.nextPage=e.nextPage,chrome.tabs.create({url:e.url},function(e){console.log(conflisttabid),""!=conflisttabid&&(chrome.tabs.remove(conflisttabid),confcontenttabid=e.id),n(confcontenttabid)})
else if("getContentList"==e.type)$.ajax({url:serverurl+"getContentList.htm",type:"post",datatype:"text",data:{content:e.content},timeout:1e5,success:function(e,t){n(e)},fail:function(e,t){}})
else if("completeconf"==e.type){console.log(conf),conf.fieldsconf=e.feildsconf
for(var o="",a="",c="",s=0;s<conf.fieldsconf.length;s++)o+=conf.fieldsconf[s].selector+"{{{{{}}}}}"
for(var s=0;s<conf.fieldsconf.length;s++)a+=conf.fieldsconf[s].text+"{{{{{}}}}}"
for(var s=0;s<conf.regexarr.length;s++)c+=conf.regexarr[s]+"{{{{{}}}}}"
o=o.substring(0,o.lastIndexOf("{{{{{}}}}}")),a=a.substring(0,a.lastIndexOf("{{{{{}}}}}")),c=c.substring(0,c.lastIndexOf("{{{{{}}}}}"))
var i={}
i.id=confid,i.title=conf.title,i.userId=conf.userid,i.targetUrl=conf.targeurl,i.listSelector=conf.regex,i.listName=c,i.fieldsSelector=o,i.fieldsName=a,i.nextSelector=conf.nextPage.nextStep+"{{{{{}}}}}"+conf.nextPage.nextPageType,i.waitTime=0,i.createtime="",i.updatetime="",console.log(i),$.ajax({url:serverurl+"saveConf.htm",type:"post",datatype:"json",data:{content:JSON.stringify(i)},timeout:1e5,success:function(e,t){var o=JSON.parse(e)
confid="","fail"==o.status?(alert("请先登录！"),chrome.tabs.create({url:"http://www.wangye.io/login.jsp",selected:!0},function(e){})):chrome.tabs.create({url:"http://www.wangye.io/pageConf.htm?id="+o.confId,selected:!0},function(e){}),n(JSON.parse(e))},fail:function(e,t){}}),chrome.tabs.remove(confcontenttabid)}else"closeconf"==e.type&&(confid="",chrome.tabs.remove(t.tab.id),chrome.tabs.remove(confcontenttabid))})
